### ISSUE TITLE
Question Regarding Importing The SDK using sbt

### ISSUE THREAD

**Issue by avshRepo** [Ingenico-NPS-Latam/nps-sdk-java#1]
I am trying to get dependency using sbt. what should i put in the libraryDependencies
i tried
libraryDependencies += "com.github.ingenico-nps-latam" %% "nps-sdk-java" % "1.1.0"

but got error in dependency resolution

**Comment by IngenicoNPSLatam** [comment]
We are checking what you say, i´ll update this issue with our findings

**Comment by IngenicoNPSLatam** [comment]
Can you provide the log of the error in dependency resolution?

**Comment by avshRepo** [comment]
solved it. it was error at my side i should have use 
libraryDependencies += "com.github.ingenico-nps-latam" % "nps-sdk-java" % "1.1.0"
and not
libraryDependencies += "com.github.ingenico-nps-latam" %% "nps-sdk-java" % "1.1.0

**Comment by IngenicoNPSLatam** [comment]
Perfect , It happens. thanks
